HealthRecords/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("reference_information/", include("reference_information.urls")),
    path("visit_records/", include("visit_records.urls")),
    path("analyzes_records/", include("analyzes_records.urls")),
    path("indicators/", include("health_indicators.urls")),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
#     # Serve static and media files from development server
#     urlpatterns += staticfiles_urlpatterns()
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analyzes_records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from analyzes_records.views import (
    CalendarView,
    CreateAnalysisView,
    LabTestDetailView,
    LabTestListView,
)

app_name = "analyzes_records"

urlpatterns = [
    path("", LabTestListView.as_view(), name="test_list"),
    path("calendar/analysis/<int:pk>", LabTestDetailView.as_view(), name="analysis"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("analysis/add/", CreateAnalysisView.as_view(), name="add_analysis"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

health_indicators/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from health_indicators.views import (
    CreateIndicatorView,
    IndicatorDetailView,
    IndicatorListView,
)

app_name = "health_indicators"

urlpatterns = [
    path("", IndicatorListView.as_view(), name="indicator_list"),
    path("indicator/<int:pk>", IndicatorDetailView.as_view(), name="indicator"),
    # path("calendar/", CalendarView.as_view(), name="calendar"),
    path("indicator/add/", CreateIndicatorView.as_view(), name="add_indicator"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reference_information/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from reference_information.views import (
    DiagnosisListView,
    DiagnosisSearchView,
    DoctorsListView,
    DoctorsSearchView,
    LaboratoryListView,
    LaboratorySearchView,
    MedInstitutionDetailView,
    MedInstitutionListView,
    MedInstitutionSearchView,
    index,
)

app_name = "reference_information"

urlpatterns = [
    path("", index, name="index"),
    path("diagnoses/", DiagnosisListView.as_view(), name="diagnosis_list"),
    path("diagnosis_search/", DiagnosisSearchView.as_view(), name="diagnosis_search"),
    path("doctors/", DoctorsListView.as_view(), name="doctors_list"),
    path("doctors_search/", DoctorsSearchView.as_view(), name="doctors_search"),
    path("labs/", LaboratoryListView.as_view(), name="laboratory_list"),
    path("labs_search/", LaboratorySearchView.as_view(), name="laboratory_search"),
    path("clinics/", MedInstitutionListView.as_view(), name="med_inst_list"),
    path(
        "clinic/<int:pk>",
        MedInstitutionDetailView.as_view(),
        name="clinic_detail",
    ),
    path("clinics_search/", MedInstitutionSearchView.as_view(), name="clinic_search"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.views import (
    ChangePasswordView,
    contact,
    edit_profile,
    index,
    login_user,
    logout_view,
    register,
)

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact, name="contact"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login_user"),
    path("logout/", logout_view, name="logout"),
    path("profile/", edit_profile, name="edit_profile"),
    path("change_password/", ChangePasswordView.as_view(), name="password_change"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

visit_records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from visit_records.views import (
    AppointmentDetailView,
    AppointmentListView,
    CreateAppointmentView,
)

app_name = "visit_records"

urlpatterns = [
    path("", AppointmentListView.as_view(), name="visit_list"),
    path("appointment/<int:pk>", AppointmentDetailView.as_view(), name="appointment"),
    path("add_appointment/", CreateAppointmentView.as_view(), name="add_appointment"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

analyzes_records/models.py
from django.contrib.auth.models import User
from django.db import models

from reference_information.models import Analysis, Laboratory


class LabTest(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    lab = models.ForeignKey(Laboratory, default=None, on_delete=models.CASCADE)
    test_date = models.DateField()
    test_time = models.TimeField(blank=True, null=True)
    previous_test = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE
    )
    analysis = models.ForeignKey(Analysis, default=None, on_delete=models.CASCADE)
    result = models.FloatField(default=0.0)
    measurement = models.CharField(max_length=50, default="")
    reference = models.TextField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to="analyzes_files/%Y/%m/%d", blank=True, null=True)

    def __str__(self):
        return (
            self.analysis.title + " / " + self.lab.title + " / " + str(self.test_date)
        )

analyzes_records/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Field, Layout, Submit
from django import forms
from easy_select2 import Select2

from analyzes_records.models import LabTest
from reference_information.models import Analysis, Laboratory


class CreateAnalysisForm(forms.ModelForm):
    lab = forms.ModelChoiceField(
        queryset=Laboratory.objects.all(),
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )
    test_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2000, 2050)))
    test_time = forms.TimeField(
        required=False, widget=forms.TimeInput(attrs={"type": "time"})
    )
    previous_test = forms.ModelChoiceField(
        queryset=LabTest.objects.all(),
        required=False,
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )
    analysis = forms.ModelChoiceField(
        queryset=Analysis.objects.all(),
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )
    result = forms.FloatField()
    measurement = forms.CharField()
    reference = forms.TextInput()
    comment = forms.TextInput()
    file = forms.FileField(
        required=False,
        widget=forms.FileInput(attrs={"class": "form-control form-control-sm"}),
    )

    class Meta:
        model = LabTest
        fields = "__all__"
        exclude = ["user"]

    def __init__(self, *args, **kwargs):
        super(CreateAnalysisForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3 create-label"
        self.helper.field_class = "form-control col-md-9"
        self.helper.layout = Layout(
            Div(
                HTML("<br>"),
                Field("lab"),
                Field("test_date"),
                Field("test_time"),
                HTML("<br>"),
                Field("previous_test"),
                Field("analysis"),
                Field("result"),
                HTML("<br>"),
                Field("measurement"),
                Field("reference"),
                HTML("<br>"),
                Field("comment"),
                Field("file"),
                HTML("<br>"),
                ButtonHolder(Submit("submit", "submit")),
            )
        )

analyzes_records/views.py
import calendar
from datetime import date, datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.views import generic
from django.views.generic import CreateView, DetailView, ListView

from analyzes_records.forms import CreateAnalysisForm
from analyzes_records.models import LabTest
from analyzes_records.utils import Calendar


class LabTestListView(ListView):
    model = LabTest
    context_object_name = "test_list"
    template_name = "analyzes_records/my_tests.html"
    paginate_by = 10

    def get_queryset(self):
        try:
            entry = LabTest.objects.filter(user=self.request.user)
        except ObjectDoesNotExist:
            print("Either the Appointment or entry doesn't exist.")
        return entry


class LabTestDetailView(LoginRequiredMixin, DetailView):
    model = LabTest
    context_object_name = "test"
    template_name = "analyzes_records/test_detail.html"


class CalendarView(generic.ListView):
    model = LabTest
    template_name = "analyzes_records/calendar.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get("month", None))
        context["prev_month"] = prev_month(d)
        context["next_month"] = next_month(d)

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context["calendar"] = mark_safe(html_cal)
        return context


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = "month=" + str(next_month.year) + "-" + str(next_month.month)
    return month


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split("-"))
        return date(year, month, day=1)
    return datetime.today()


class CreateAnalysisView(LoginRequiredMixin, CreateView):
    form_class = CreateAnalysisForm
    template_name = "analyzes_records/add_test.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.is_valid():
            form.save()

        return super(CreateAnalysisView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("analyzes_records:analysis", kwargs={"pk": self.object.pk})

templates/analyzes_records/add_test.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Analyzes{% endblock %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark z-index-9  fixed-top" id="mainNav">

        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav navbar-sidenav background-main-color admin-nav" id="admin-nav">
                <li class="nav-item">
                    <span class="nav-title-text">Main</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url "users:index" %}">
                        <i class="fas fa-fw fa-home"></i><span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "visit_records:visit_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Appointments</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:test_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Analyzes</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:calendar" %}">
                        <i class="fa fa-fw fa-calendar"></i>
                        <span class="nav-link-text">Analyzes Calendar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "health_indicators:indicator_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Indicators</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">Add Pages</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "visit_records:add_appointment" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Appointment</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "analyzes_records:add_analysis" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Analysis</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "health_indicators:add_indicator" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Indicator</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">User Area</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Profile">
                    <a class="nav-link" href="{% url "users:edit_profile" %}">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="nav-link-text">My Profile</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sing Out">
                    <a class="nav-link" href="{% url "users:logout" %}" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out-alt"></i>
                        <span class="nav-link-text">Sing Out</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

    <div class="content-wrapper">
        <div class="container-fluid overflow-hidden">
            <div id="page-title" class="padding-tb-30px gradient-white">
                <div class="container">
                    <ol class="breadcrumb opacity-5">
                        <li><a href="{% url "users:index" %}">Home</a></li>
                        <li><a href="{% url "analyzes_records:test_list" %}">Analyzes</a></li>
                        <li class="active">Add Analysis</li>
                    </ol>
                    <h1 class="font-weight-300">Add Analysis</h1>
                </div>
            </div>
            <div class="form-output">
                <div class="container margin-bottom-10px">
                    <div id="log-in" class="site-form form-control box-shadow border-radius-10">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ form.media.js }}
{% endblock %}

templates/analyzes_records/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>HealthRecords</title>
    <meta name="author" content="Nile-Theme">
    <meta name="robots" content="index follow">
    <meta name="googlebot" content="index follow">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="keywords"
          content="directory, doctor, doctor directory, Health directory, listing, map, medical, medical directory, professional directory, reservation, reviews">
    <meta name="description" content="Health Care & Medical Services Directory">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800%7CPoppins:300i,300,400,700,400i,500%7CDancing+Script:700%7CDancing+Script:700"
          rel="stylesheet">
    <!-- animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
    <!-- owl Carousel assets -->
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- hover anmation -->
    <link rel="stylesheet" href="{% static 'css/hover-min.css' %}">
    <!-- flag icon -->
    <link rel="stylesheet" href="{% static 'css/flag-icon.min.css' %}">
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- colors -->
    <link rel="stylesheet" href="{% static 'css/colors/main.css' %}">
    <!-- elegant icon -->
    <link rel="stylesheet" href="{% static 'css/elegant_icon.css' %}">
    <!-- admin style -->
    <link rel="stylesheet" href="{% static '/css/sb-admin.css' %}">
    <!-- jquery library  -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <!-- fontawesome  -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark z-index-9  fixed-top" id="mainNav">

        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav navbar-sidenav background-main-color admin-nav" id="admin-nav">
                <li class="nav-item">
                    <span class="nav-title-text">Main</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url "users:index" %}">
                        <i class="fas fa-fw fa-home"></i><span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "visit_records:visit_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Appointments</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:test_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Analyzes</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:calendar" %}">
                        <i class="fa fa-fw fa-calendar"></i>
                        <span class="nav-link-text">Analyzes Calendar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "health_indicators:indicator_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Indicators</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">Add Pages</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "visit_records:add_appointment" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Appointment</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "analyzes_records:add_analysis" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Analysis</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "health_indicators:add_indicator" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Indicator</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">User Area</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Profile">
                    <a class="nav-link" href="{% url "users:edit_profile" %}">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="nav-link-text">My Profile</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sing Out">
                    <a class="nav-link" href="{% url "users:logout" %}" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out-alt"></i>
                        <span class="nav-link-text">Sing Out</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

<header>
    <div id="fixed-header-dark" class="header-output fixed-header">
        <div class="container header-in">


            <div class="row">
                <div class="col-lg-2 col-md-12">
                    <a id="logo" href="{% url "users:index" %}" class="d-inline-block margin-tb-15px"><img
                            src="{% static 'img/logo-1.png' %}" alt="">
                        <h6 class="text-medium text-main-color font-weight-300 margin-bottom-15px">HealthRecords</h6>
                    </a>
                    <a class="mobile-toggle padding-13px background-main-color" href="#"><i class="fas fa-bars"></i></a>
                </div>
                <div class="col-lg-7 col-md-12 position-inherit">
                    <ul id="menu-main" class="nav-menu float-lg-right link-padding-tb-20px">
                        <li class="has-dropdown"><a href="{% url "visit_records:visit_list" %}">Appointments</a>
                            <ul class="sub-menu">
                                {% if request.user.is_authenticated %}
                                    <li><a href="{% url "visit_records:visit_list" %}">My Appointments</a></li>
                                    <li><a href="{% url "visit_records:add_appointment" %}">Add an Appointment</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="has-dropdown"><a href="{% url "visit_records:visit_list" %}">Analyzes</a>
                            <ul class="sub-menu">
                                {% if request.user.is_authenticated %}
                                    <li><a href="{% url "visit_records:visit_list" %}">My Analyzes</a></li>
                                    <li><a href="{% url "visit_records:add_appointment" %}">Add an Analysis</a></li>
                                    <li><a href="{% url "analyzes_records:calendar" %}">Calendar</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="has-dropdown"><a href="{% url "reference_information:index" %}">Reference Information
                            <ul class="sub-menu">
                                <li><a href="{% url "reference_information:diagnosis_list" %}">Diagnoses</a></li>
                                <li><a href="{% url "reference_information:doctors_list" %}">Doctors</a></li>
                                <li><a href="{% url "reference_information:med_inst_list" %}">Clinics</a></li>
                                <li><a href="{% url "reference_information:laboratory_list" %}">Laboratories</a></li>
                            </ul>
                        </a>
                        </li>
                        <li><a href="{% url "users:contact" %}">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-12">

                    {% if request.user.is_authenticated %}

                        <hr class="margin-bottom-0px d-block d-sm-none">
                        <div class="padding-lr-20px d-inline-block text-up-small">
                            Hello, <a href="{% url 'users:edit_profile' %}"
                                      class="margin-tb-20px d-inline-block text-up-small ">
                            {{ request.user.username }}</a>
                        </div>
                        <a href="{% url "users:logout" %}"
                           class="padding-lr-20px d-inline-block text-up-small ">
                            <i class="far fa-user"></i> Sing Out</a>
                    {% else %}
                        <hr class="margin-bottom-0px d-block d-sm-none">
                        <a href="{% url "users:login_user" %}"
                           class="margin-tb-20px d-inline-block text-up-small float-left float-lg-right">
                            <i class="far fa-user"></i> Sign In</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>
<!-- // Header  -->
<section class="banner padding-tb-200px sm-ptb-80px background-overlay"
         style="background-image: url('{% static 'img/background.jpg' %}');">
    <div class="container z-index-2 position-relative">
        <div class="content-wrapper">
            <div class="container-fluid overflow-hidden">
                <div class="margin-tb-10px">
                    <div class="container">
                        <div class="clearfix">
                            <a class="btn btn-info left" href="{% url 'analyzes_records:calendar' %}?{{ prev_month }}">
                                Previous
                                Month </a>
                            <a class="btn btn-info right" href="{% url "analyzes_records:calendar" %}?{{ next_month }}">
                                Next Month </a>
                        </div>

                        {{ calendar }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'js/sticky-sidebar.js' %}"></script>
<script src="{% static 'js/YouTubePopUp.jquery.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>