HealthRecords/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("reference_information/", include("reference_information.urls")),
    path("visit_records/", include("visit_records.urls")),
    path("analyzes_records/", include("analyzes_records.urls")),
    path("indicators/", include("health_indicators.urls")),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
#     # Serve static and media files from development server
#     urlpatterns += staticfiles_urlpatterns()
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analyzes_records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from analyzes_records.views import (
    CalendarView,
    CreateAnalysisView,
    LabTestDetailView,
    LabTestListView,
)

app_name = "analyzes_records"

urlpatterns = [
    path("", LabTestListView.as_view(), name="test_list"),
    path("calendar/analysis/<int:pk>", LabTestDetailView.as_view(), name="analysis"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("analysis/add/", CreateAnalysisView.as_view(), name="add_analysis"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

health_indicators/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from health_indicators.views import (
    CreateIndicatorView,
    IndicatorDetailView,
    IndicatorListView,
)

app_name = "health_indicators"

urlpatterns = [
    path("", IndicatorListView.as_view(), name="indicator_list"),
    path("indicator/<int:pk>", IndicatorDetailView.as_view(), name="indicator"),
    # path("calendar/", CalendarView.as_view(), name="calendar"),
    path("indicator/add/", CreateIndicatorView.as_view(), name="add_indicator"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reference_information/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from reference_information.views import (
    DiagnosisListView,
    DiagnosisSearchView,
    DoctorsListView,
    DoctorsSearchView,
    LaboratoryListView,
    LaboratorySearchView,
    MedInstitutionDetailView,
    MedInstitutionListView,
    MedInstitutionSearchView,
    index,
)

app_name = "reference_information"

urlpatterns = [
    path("", index, name="index"),
    path("diagnoses/", DiagnosisListView.as_view(), name="diagnosis_list"),
    path("diagnosis_search/", DiagnosisSearchView.as_view(), name="diagnosis_search"),
    path("doctors/", DoctorsListView.as_view(), name="doctors_list"),
    path("doctors_search/", DoctorsSearchView.as_view(), name="doctors_search"),
    path("labs/", LaboratoryListView.as_view(), name="laboratory_list"),
    path("labs_search/", LaboratorySearchView.as_view(), name="laboratory_search"),
    path("clinics/", MedInstitutionListView.as_view(), name="med_inst_list"),
    path(
        "clinic/<int:pk>",
        MedInstitutionDetailView.as_view(),
        name="clinic_detail",
    ),
    path("clinics_search/", MedInstitutionSearchView.as_view(), name="clinic_search"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.views import (
    ChangePasswordView,
    contact,
    edit_profile,
    index,
    login_user,
    logout_view,
    register,
)

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact, name="contact"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login_user"),
    path("logout/", logout_view, name="logout"),
    path("profile/", edit_profile, name="edit_profile"),
    path("change_password/", ChangePasswordView.as_view(), name="password_change"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

visit_records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from visit_records.views import (
    AppointmentDetailView,
    AppointmentListView,
    CreateAppointmentView,
)

app_name = "visit_records"

urlpatterns = [
    path("", AppointmentListView.as_view(), name="visit_list"),
    path("appointment/<int:pk>", AppointmentDetailView.as_view(), name="appointment"),
    path("add_appointment/", CreateAppointmentView.as_view(), name="add_appointment"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

visit_records/models.py
from django.contrib.auth.models import User
from django.db import models

from reference_information.models import (
    Analysis,
    Diagnosis,
    Doctor,
    MedCategory,
    MedInstitution,
)


class Appointment(models.Model):

    STATUS_CHOICES = [
        ("0", "Scheduled"),
        ("1", "Completed"),
    ]

    class Meta:
        verbose_name_plural = "Appointments"

    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    med_category = models.ForeignKey(
        MedCategory, default=None, on_delete=models.CASCADE
    )
    appointment_date = models.DateField()
    appointment_time = models.TimeField(blank=True, null=True)
    reminder = models.BooleanField(default=False, help_text="Create a reminder?")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    previous_appointment = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE
    )
    clinic = models.ForeignKey(MedInstitution, default=None, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, default=None, on_delete=models.CASCADE)
    examination_protocol = models.TextField(
        blank=True, null=True, help_text="Patient's complaints"
    )
    conclusion = models.TextField(
        blank=True, null=True, help_text="Diagnoses and health problems"
    )
    diagnosis = models.ManyToManyField(
        Diagnosis,
        blank=False,
        related_name="appointment_diagnoses",
        through="AppointmentDiagnosis",
    )
    analysis = models.ManyToManyField(
        Analysis,
        blank=False,
        related_name="appointment_analyzes",
        through="AppointmentAnalysis",
    )
    recommendations = models.TextField(
        blank=True, null=True, help_text="Treatment recommendations"
    )
    file = models.FileField(
        upload_to="appointment_files/%Y/%m/%d", blank=True, null=True
    )

    def __str__(self):
        return (
            self.med_category.title
            + ", "
            + self.doctor.name
            + ", "
            + str(self.appointment_date)
        )


class AppointmentDiagnosis(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    diagnosis = models.ForeignKey(Diagnosis, on_delete=models.CASCADE)


class AppointmentAnalysis(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    analysis = models.ForeignKey(Analysis, on_delete=models.CASCADE)

visit_records/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Field, Fieldset, Layout, Submit
from django import forms
from django.forms.models import inlineformset_factory
from easy_select2 import Select2

from reference_information.models import Doctor, MedCategory, MedInstitution
from visit_records.custom_layout_object import Formset
from visit_records.models import Appointment, AppointmentAnalysis, AppointmentDiagnosis


class CreateAppointmentForm(forms.ModelForm):
    STATUS_CHOICES = [
        ("0", "Scheduled"),
        ("1", "Completed"),
    ]

    med_category = forms.ModelChoiceField(
        queryset=MedCategory.objects.all(),
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )

    appointment_date = forms.DateField(
        widget=forms.SelectDateWidget(years=range(2000, 2050))
    )

    appointment_time = forms.TimeField(
        required=False, widget=forms.TimeInput(attrs={"type": "time"})
    )

    reminder = forms.CheckboxInput()

    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect)

    previous_appointment = forms.ModelChoiceField(
        queryset=Appointment.objects.all(),
        required=False,
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )

    clinic = forms.ModelChoiceField(
        queryset=MedInstitution.objects.all(),
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )

    doctor = forms.ModelChoiceField(
        queryset=Doctor.objects.all(),
        widget=Select2(attrs={"class": "form-control form-control-sm"}),
    )

    examination_protocol = forms.TextInput()

    conclusion = forms.TextInput()

    recommendations = forms.TextInput()

    file = forms.FileField(
        required=False,
        widget=forms.FileInput(attrs={"class": "form-control form-control-sm"}),
    )

    class Meta:
        model = Appointment
        fields = "__all__"
        exclude = ["user", "analysis", "diagnosis"]

    def __init__(self, *args, **kwargs):
        super(CreateAppointmentForm, self).__init__(*args, **kwargs)
        self.fields["med_category"].label = "Category"
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3 create-label"
        self.helper.field_class = "form-control col-md-9"
        self.helper.layout = Layout(
            Div(
                HTML("<br>"),
                Field("med_category"),
                Field("appointment_date"),
                Field("appointment_time"),
                HTML("<br>"),
                Field("reminder"),
                Field("status"),
                Field("previous_appointment"),
                Field("clinic"),
                Field("doctor"),
                HTML("<br>"),
                Field("examination_protocol"),
                Field("conclusion"),
                HTML("<br>"),
                Fieldset("Diagnoses", Formset("diagnoses")),
                Fieldset("Analyzes", Formset("analyzes")),
                Field("recommendations"),
                Field("file"),
                HTML("<br>"),
                ButtonHolder(Submit("submit", "submit")),
            )
        )


class AppointmentDiagnosisForm(forms.ModelForm):
    class Meta:
        model = AppointmentDiagnosis
        exclude = ()


class AppointmentAnalysisForm(forms.ModelForm):
    class Meta:
        model = AppointmentAnalysis
        exclude = ()


AppointmentDiagnosisFormSet = inlineformset_factory(
    Appointment,
    AppointmentDiagnosis,
    form=AppointmentDiagnosisForm,
    fields="__all__",
    extra=3,
    can_delete=True,
    widgets={
        "diagnosis": forms.Select(attrs={"class": "form-control form-control-sm"}),
    },
)


AppointmentAnalysisFormSet = inlineformset_factory(
    Appointment,
    AppointmentAnalysis,
    form=AppointmentAnalysisForm,
    fields="__all__",
    extra=3,
    can_delete=True,
    widgets={
        "analysis": forms.Select(attrs={"class": "form-control form-control-sm"}),
    },
)

visit_records/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView

from visit_records.forms import (
    AppointmentAnalysisFormSet,
    AppointmentDiagnosisFormSet,
    CreateAppointmentForm,
)
from visit_records.models import Appointment, AppointmentAnalysis, AppointmentDiagnosis


class AppointmentListView(ListView):
    model = Appointment
    context_object_name = "appointment_list"
    template_name = "visit_records/my_appointments.html"
    paginate_by = 10

    def get_queryset(self):
        try:
            entry = Appointment.objects.filter(user=self.request.user)
        except ObjectDoesNotExist:
            print("Either the Appointment or entry doesn't exist.")
        return entry


class AppointmentDetailView(LoginRequiredMixin, DetailView):
    model = Appointment
    context_object_name = "appointment"
    template_name = "visit_records/appointment_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["diagnoses"] = AppointmentDiagnosis.objects.filter(
            appointment_id=self.kwargs.get("pk")
        ).distinct("diagnosis__title")
        context["analyzes"] = AppointmentAnalysis.objects.filter(
            appointment_id=self.kwargs.get("pk")
        ).distinct("analysis__title")
        return context


class CreateAppointmentView(LoginRequiredMixin, CreateView):
    form_class = CreateAppointmentForm
    template_name = "visit_records/add_appointment.html"

    def get_context_data(self, **kwargs):
        context = super(CreateAppointmentView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["diagnoses"] = AppointmentDiagnosisFormSet(self.request.POST)
            context["analyzes"] = AppointmentAnalysisFormSet(self.request.POST)
        else:
            context["diagnoses"] = AppointmentDiagnosisFormSet()
            context["analyzes"] = AppointmentAnalysisFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        appointment = self.kwargs.get("pk")
        diagnoses = context["diagnoses"]
        analyzes = context["analyzes"]

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if diagnoses.is_valid():
                diagnoses.instance = self.object
                diagnoses.save()
            if analyzes.is_valid():
                analyzes.instance = self.object
                analyzes.save()
        return super(CreateAppointmentView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("visit_records:appointment", kwargs={"pk": self.object.pk})

templates/visit_records/add_appointment.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Appointments{% endblock %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark z-index-9  fixed-top" id="mainNav">

        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav navbar-sidenav background-main-color admin-nav" id="admin-nav">
                <li class="nav-item">
                    <span class="nav-title-text">Main</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url "users:index" %}">
                        <i class="fas fa-fw fa-home"></i><span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "visit_records:visit_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Appointments</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:test_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Analyzes</span>
                    </a>
                </li>
                 <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:calendar" %}">
                        <i class="fa fa-fw fa-calendar"></i>
                        <span class="nav-link-text">Analyzes Calendar</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">Add Pages</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "visit_records:add_appointment" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Appointment</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "analyzes_records:add_analysis" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Analysis</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">User Area</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Profile">
                    <a class="nav-link" href="{% url "users:edit_profile" %}">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="nav-link-text">My Profile</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sing Out">
                    <a class="nav-link" href="{% url "users:logout" %}" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out-alt"></i>
                        <span class="nav-link-text">Sing Out</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

    <div class="content-wrapper">
        <div class="container-fluid overflow-hidden">
            <div id="page-title" class="padding-tb-30px gradient-white">
                <div class="container">
                    <ol class="breadcrumb opacity-5">
                        <li><a href="{% url "users:index" %}">Home</a></li>
                        <li><a href="{% url "visit_records:visit_list" %}">Appointments</a></li>
                        <li class="active">Add Appointment</li>
                    </ol>
                    <h1 class="font-weight-300">Add Appointment</h1>
                </div>
            </div>
            <div class="form-output">
                <div class="container margin-bottom-10px">
                    <div id="log-in" class="site-form form-control box-shadow border-radius-10">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ form.media.js }}
{% endblock %}

templates/visit_records/appointment_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Appointment{% endblock %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark z-index-9  fixed-top" id="mainNav">

        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav navbar-sidenav background-main-color admin-nav" id="admin-nav">
                <li class="nav-item">
                    <span class="nav-title-text">Main</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url "users:index" %}">
                        <i class="fas fa-fw fa-home"></i><span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "visit_records:visit_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Appointments</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:test_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Analyzes</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:calendar" %}">
                        <i class="fa fa-fw fa-calendar"></i>
                        <span class="nav-link-text">Analyzes Calendar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "health_indicators:indicator_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Indicators</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">Add Pages</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "visit_records:add_appointment" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Appointment</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "analyzes_records:add_analysis" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Analysis</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "health_indicators:add_indicator" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Indicator</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">User Area</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Profile">
                    <a class="nav-link" href="{% url "users:edit_profile" %}">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="nav-link-text">My Profile</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sing Out">
                    <a class="nav-link" href="{% url "users:logout" %}" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out-alt"></i>
                        <span class="nav-link-text">Sing Out</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

    <div class="content-wrapper">
        <div class="container-fluid overflow-hidden">
            <div id="page-title" class="padding-tb-30px gradient-white">
                <div class="container">
                    <ol class="breadcrumb opacity-5">
                        <li><a href="{% url "users:index" %}">Home</a></li>
                        <li><a href="{% url "visit_records:visit_list" %}">My Appointments</a></li>
                        <li class="active">Appointment</li>
                    </ol>
                    <h1 class="font-weight-300">{{ appointment.med_category }} / {{ appointment.appointment_date }}
                        / {{ appointment.doctor }}</h1>
                </div>
            </div>


            <div class="margin-tb-10px">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="margin-bottom-30px box-shadow">
                                <div class="padding-30px background-white">
                                    <h3>
                                        <i class="far fa-hospital margin-right-10px text-main-color"></i>{{ appointment.med_category }}
                                    </h3>
                                    <span class="margin-right-20px text-small">Date:  <a
                                            href="#">{{ appointment.appointment_date }}</a></span>
                                    {% if appointment.appointment_time is not Null %}
                                        <span class="margin-right-20px text-small">Time:  <a
                                                href="#">{{ appointment.appointment_time }}</a></span>
                                    {% endif %}
                                    <br>
                                    {% if appointment.previous_appointment is not Null %}
                                        <span class="margin-right-20px text-small">Previous appointment:
                                            <a href="{% url "visit_records:appointment" appointment.previous_appointment.id %}">
                                            {{ appointment.previous_appointment.appointment_date }}</a></span>
                                    {% endif %}
                                    <div class="entry-content">
                                        <br>
                                        <span class="margin-right-20px text-large">Clinic: <a
                                                href="{% url "reference_information:clinic_detail" appointment.clinic.id %}">{{ appointment.clinic }}</a></span>
                                        <br>
                                        <span class="margin-right-20px text-large">Doctor: {{ appointment.doctor }}</span>
                                        <br><br>
                                        <h5>Examination protocol: </h5>
                                        <p>{{ appointment.examination_protocol }}</p>
                                        <h5>Conclusion: </h5>
                                        <p>{{ appointment.conclusion }}</p>
                                        {% if diagnoses %}
                                            <h5>Diagnoses: </h5>
                                            {% for d in diagnoses %}
                                                {{ d.diagnosis }}<br>
                                            {% endfor %}
                                        {% endif %}
                                        <br>
                                        {% if analyzes %}
                                            <h5>Examination plan: </h5>
                                            {% for h in analyzes %}
                                                {{ h.analysis }}<br>
                                            {% endfor %}
                                        {% endif %}
                                        <br>
                                        <h5>Recommendations: </h5>
                                        <p>{{ appointment.recommendations }}</p>
                                        {% if appointment.file %}
                                            <a href="{{ appointment.file.url }}" target="_blank">
                                                <button class="btn btn-outline-warning mr-3">Download file</button>&nbsp;
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/visit_records/formset.html
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
<table>
    {{ formset.management_form|crispy }}
    {% for form in formset.forms %}
        <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
            {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script src="{% static "js/jquery.formset.js" %}">
</script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>