HealthRecords/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("reference_information/", include("reference_information.urls")),
    path("visit_records/", include("visit_records.urls")),
    path("analyzes_records/", include("analyzes_records.urls")),
    path("indicators/", include("health_indicators.urls")),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
#     # Serve static and media files from development server
#     urlpatterns += staticfiles_urlpatterns()
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reference_information/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from reference_information.views import (
    DiagnosisListView,
    DiagnosisSearchView,
    DoctorsListView,
    DoctorsSearchView,
    LaboratoryListView,
    LaboratorySearchView,
    MedInstitutionDetailView,
    MedInstitutionListView,
    MedInstitutionSearchView,
    index,
)

app_name = "reference_information"

urlpatterns = [
    path("", index, name="index"),
    path("diagnoses/", DiagnosisListView.as_view(), name="diagnosis_list"),
    path("diagnosis_search/", DiagnosisSearchView.as_view(), name="diagnosis_search"),
    path("doctors/", DoctorsListView.as_view(), name="doctors_list"),
    path("doctors_search/", DoctorsSearchView.as_view(), name="doctors_search"),
    path("labs/", LaboratoryListView.as_view(), name="laboratory_list"),
    path("labs_search/", LaboratorySearchView.as_view(), name="laboratory_search"),
    path("clinics/", MedInstitutionListView.as_view(), name="med_inst_list"),
    path(
        "clinic/<int:pk>",
        MedInstitutionDetailView.as_view(),
        name="clinic_detail",
    ),
    path("clinics_search/", MedInstitutionSearchView.as_view(), name="clinic_search"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.views import (
    ChangePasswordView,
    contact,
    edit_profile,
    index,
    login_user,
    logout_view,
    register,
)

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact, name="contact"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login_user"),
    path("logout/", logout_view, name="logout"),
    path("profile/", edit_profile, name="edit_profile"),
    path("change_password/", ChangePasswordView.as_view(), name="password_change"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reference_information/models.py
from django.db import models


class Allergy(models.Model):
    class Meta:
        verbose_name_plural = "Allergies"

    ALLERGY_TYPE_CHOICES = [
        ("0", "Household allergy"),
        ("1", "Pollen allergy"),
        ("2", "Animal allergy"),
        ("3", "Fungal allergy"),
        ("4", "Insect allergy"),
        ("5", "Food allergy"),
        ("6", "Drug allergy"),
        ("7", "Industrial allergy"),
    ]

    title = models.CharField(max_length=100)
    allergy_type = models.CharField(
        max_length=1, choices=ALLERGY_TYPE_CHOICES, blank=True, null=True
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Diagnosis(models.Model):
    class Meta:
        verbose_name_plural = "Diagnoses"

    icd_code = models.CharField(max_length=10)
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Analysis(models.Model):
    class Meta:
        verbose_name_plural = "Analyzes"

    test_code = models.CharField(max_length=10)
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class DoctorSpecialization(models.Model):
    class Meta:
        verbose_name_plural = "Doctor's specializations"

    title = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class MedInstitution(models.Model):
    class Meta:
        verbose_name_plural = "Med institutions"

    title = models.CharField(max_length=300)
    address_1 = models.CharField(max_length=300)
    address_2 = models.CharField(max_length=300, blank=True, null=True)
    address_3 = models.CharField(max_length=300, blank=True, null=True)
    address_4 = models.CharField(max_length=300, blank=True, null=True)
    address_5 = models.CharField(max_length=300, blank=True, null=True)
    phone_1 = models.CharField(max_length=20, blank=True, null=True)
    phone_2 = models.CharField(max_length=20, blank=True, null=True)
    phone_3 = models.CharField(max_length=20, blank=True, null=True)
    site = models.URLField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.title


class Laboratory(models.Model):
    class Meta:
        verbose_name_plural = "Laboratories"

    title = models.CharField(max_length=300)
    address = models.CharField(max_length=300, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    site = models.URLField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.title


class MedCategory(models.Model):
    class Meta:
        verbose_name_plural = "Medicine categories"

    title = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Doctor(models.Model):
    class Meta:
        verbose_name_plural = "Doctors"

    name = models.CharField(max_length=100)
    speciality = models.ForeignKey(
        DoctorSpecialization,
        blank=True,
        null=True,
        default=None,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        MedCategory, blank=True, null=True, default=None, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Symptom(models.Model):
    class Meta:
        verbose_name_plural = "Symptoms"

    title = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

reference_information/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import Diagnosis, Doctor, Laboratory, MedInstitution


def index(request):
    return render(request, "reference_information/index.html")


class DiagnosisListView(ListView):
    model = Diagnosis
    context_object_name = "diagnosis_list"
    template_name = "reference_information/lists/diagnosis.html"
    paginate_by = 50


class DiagnosisSearchView(ListView):
    model = Diagnosis
    template_name = "reference_information/search/diagnosis_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Diagnosis.objects.filter(
            Q(title__icontains=query) | Q(icd_code__icontains=query)
        )

        if not object_list:
            object_list = Diagnosis.objects.all()

        return object_list


class DoctorsListView(ListView):
    model = Doctor
    context_object_name = "doctors_list"
    template_name = "reference_information/lists/doctors.html"
    paginate_by = 10


class DoctorsSearchView(ListView):
    model = Doctor
    template_name = "reference_information/search/doctors_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Doctor.objects.filter(
            Q(name__icontains=query) | Q(speciality__title__icontains=query)
        )

        if not object_list:
            object_list = Doctor.objects.all()

        return object_list


class LaboratoryListView(ListView):
    model = Laboratory
    context_object_name = "laboratory_list"
    template_name = "reference_information/lists/laboratories.html"
    paginate_by = 10


class LaboratorySearchView(ListView):
    model = Laboratory
    template_name = "reference_information/search/laboratory_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Laboratory.objects.filter(Q(title__icontains=query))

        if not object_list:
            object_list = Laboratory.objects.all()

        return object_list


class MedInstitutionListView(ListView):
    model = MedInstitution
    context_object_name = "med_inst_list"
    template_name = "reference_information/lists/med_institutions.html"
    paginate_by = 10


class MedInstitutionDetailView(DetailView):
    model = MedInstitution
    context_object_name = "clinic"
    template_name = "reference_information/details/clinic_detail.html"


class MedInstitutionSearchView(ListView):
    model = MedInstitution
    template_name = "reference_information/search/clinic_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = MedInstitution.objects.filter(Q(title__icontains=query))

        if not object_list:
            object_list = MedInstitution.objects.all()

        return object_list

templates/reference_information/lists/diagnosis.html
{% extends "base.html" %}

{% load static %}

{% block title %}Diagnosis{% endblock %}

{% block content %}
  
{% endblock %}

templates/reference_information/lists/doctors.html
{% extends "base.html" %}

{% load static %}

{% block title %}Doctors{% endblock %}

{% block content %}

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container">
            <ol class="breadcrumb opacity-5">
                <li><a href="{% url "users:index" %}">Home</a></li>
                <li><a href="{% url "reference_information:index" %}">Reference information</a></li>
                <li class="active">Doctors</li>
            </ol>
            <h1 class="font-weight-300">Doctors</h1>
        </div>
    </div>


    <div class="margin-tb-30px">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <div class="row">
                        {% for doctor in doctors_list %}
                            <!-- Doctor -->
                            <div class="col-lg-4 col-md-6 hvr-bob sm-mb-45px">
                                <div class="background-white box-shadow margin-bottom-45px">
                                    <div class="padding-lr-30px padding-bottom-30px">
                                        <div class="pull-top-40px z-index-2 position-relative">
                                            <span class="text-grey-2">{{ doctor.category }}</span>
                                            <h5 class="margin-tb-15px text-large">{{ doctor.name }}</h5>
                                            <h5 class="margin-tb-15px text-blue">{{ doctor.speciality }}</h5>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!-- // Doctor -->
                        {% endfor %}
                    </div>
                    {% if is_paginated %}
                        <ul class="pagination pagination-md ">
                            <li class="page-item">
                                {% if page_obj.has_previous %}
                                    <a class="page-link rounded-0" href="?page=1">&laquo; first</a>
                                    <a class="page-link rounded-0"
                                       href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                                {% endif %}
                            </li>

                            <li class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </li>

                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link rounded-0"
                                       href="?page={{ page_obj.next_page_number }}">Next</a>
                                    <a class="page-link rounded-0"
                                       href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                                </li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>


                <div class="col-lg-4">

                    <div class="background-white border-radius-10 margin-bottom-45px">
                        <div class="padding-25px">
                            <h3 class="margin-lr-20px"><i
                                    class="fas fa-search margin-right-10px text-main-color"></i> Search Filter</h3>
                            <!-- Listing Search -->
                            <div class="listing-search">
                                <form action="{% url 'reference_information:doctors_search' %}" method="get">
                                    <div class="keywords margin-bottom-20px">
                                        <input name="q" class="listing-form first border-radius-10" type="text"
                                               placeholder="Name or icd code..." value="">
                                    </div>
                                </form>
                            </div>
                            <!-- // Listing Search -->
                        </div>
                    </div>


                    <div class="featured-category">
                        <div class="row">

                            <div class="col-6 wow fadeInUp" data-wow-delay="0.6s">
                                <a href="{% url "reference_information:diagnosis_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px opacity-7">
                                            <img src="{% static "/img/icon/categorie-4.png" %}" alt="">
                                        </div>
                                        Diagnoses
                                    </div>
                                </a>
                            </div>

                            <div class="col-6 margin-bottom-30px wow fadeInUp">
                                <a href="{% url "reference_information:doctors_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px opacity-7">
                                            <img src="{% static "/img/icon/categorie-1.png" %}" alt="">
                                        </div>
                                        Doctors
                                    </div>
                                </a>
                            </div>

                            <div class="col-6 margin-bottom-30px wow fadeInUp" data-wow-delay="0.2s">
                                <a href="{% url "reference_information:med_inst_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px opacity-7">
                                            <img src="{% static "/img/icon/categorie-2.png" %}" alt="">
                                        </div>
                                        Clinics
                                    </div>
                                </a>
                            </div>

                            <div class="col-6 wow fadeInUp" data-wow-delay="0.4s">
                                <a href="{% url "reference_information:laboratory_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px">
                                            <img src="{% static "/img/icon/categorie-3.png" %}" alt="">
                                        </div>
                                        Labs
                                    </div>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/reference_information/lists/med_institutions.html
{% extends "base.html" %}

{% load static %}

{% block title %}Clinics{% endblock %}

{% block content %}

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container">
            <ol class="breadcrumb opacity-5">
                <li><a href="{% url "users:index" %}">Home</a></li>
                <li><a href="{% url "reference_information:index" %}">Reference information</a></li>
                <li class="active">Clinics</li>
            </ol>
            <h1 class="font-weight-300">Clinics</h1>
        </div>
    </div>


    <div class="margin-tb-30px">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <div class="row">
                        {% for clinic in med_inst_list %}
                            <!-- Clinic -->
                            <div class="col-lg-4 col-md-6 hvr-bob sm-mb-45px">
                                <div class="background-white box-shadow margin-bottom-45px">
                                    <div class="padding-lr-30px padding-bottom-30px">
                                        <div class="pull-top-40px z-index-2 position-relative">
                                            <br>
                                            <h5 class="margin-tb-15px"><a href="{% url "reference_information:clinic_detail" clinic.id %}">{{ clinic.title }}</a></h5>
                                            <span class="text-grey-2">{{ clinic.phone_1 }}</span>
                                            <a class="text-blue" target="_blank" href="{{ clinic.site }}">{{ clinic.site }}</a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!-- // Clinic -->
                        {% endfor %}
                    </div>
                    {% if is_paginated %}
                        <ul class="pagination pagination-md ">
                            <li class="page-item">
                                {% if page_obj.has_previous %}
                                    <a class="page-link rounded-0" href="?page=1">&laquo; first</a>
                                    <a class="page-link rounded-0"
                                       href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                                {% endif %}
                            </li>

                            <li class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </li>

                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link rounded-0"
                                       href="?page={{ page_obj.next_page_number }}">Next</a>
                                    <a class="page-link rounded-0"
                                       href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                                </li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>


                <div class="col-lg-4">

                    <div class="background-white border-radius-10 margin-bottom-45px">
                        <div class="padding-25px">
                            <h3 class="margin-lr-20px"><i
                                    class="fas fa-search margin-right-10px text-main-color"></i> Search Filter</h3>
                            <!-- Listing Search -->
                            <div class="listing-search">
                                <form action="{% url 'reference_information:clinic_search' %}" method="get">
                                    <div class="keywords margin-bottom-20px">
                                        <input name="q" class="listing-form first border-radius-10" type="text"
                                               placeholder="Clinic name..." value="">
                                    </div>
                                </form>
                            </div>
                            <!-- // Listing Search -->
                        </div>
                    </div>


                    <div class="featured-category">
                        <div class="row">

                            <div class="col-6 wow fadeInUp" data-wow-delay="0.6s">
                                <a href="{% url "reference_information:diagnosis_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px opacity-7">
                                            <img src="{% static "/img/icon/categorie-4.png" %}" alt="">
                                        </div>
                                        Diagnoses
                                    </div>
                                </a>
                            </div>

                            <div class="col-6 margin-bottom-30px wow fadeInUp">
                                <a href="{% url "reference_information:doctors_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px opacity-7">
                                            <img src="{% static "/img/icon/categorie-1.png" %}" alt="">
                                        </div>
                                        Doctors
                                    </div>
                                </a>
                            </div>

                            <div class="col-6 margin-bottom-30px wow fadeInUp" data-wow-delay="0.2s">
                                <a href="{% url "reference_information:med_inst_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px opacity-7">
                                            <img src="{% static "/img/icon/categorie-2.png" %}" alt="">
                                        </div>
                                        Clinics
                                    </div>
                                </a>
                            </div>

                            <div class="col-6 wow fadeInUp" data-wow-delay="0.4s">
                                <a href="{% url "reference_information:laboratory_list" %}"
                                   class="d-block border-radius-15 hvr-float hvr-sh2">
                                    <div class="background-main-color text-white border-radius-15 padding-30px text-center opacity-hover-7">
                                        <div class="icon margin-bottom-15px">
                                            <img src="{% static "/img/icon/categorie-3.png" %}" alt="">
                                        </div>
                                        Labs
                                    </div>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}