HealthRecords/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("reference_information/", include("reference_information.urls")),
    path("visit_records/", include("visit_records.urls")),
    path("analyzes_records/", include("analyzes_records.urls")),
    path("indicators/", include("health_indicators.urls")),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
#     # Serve static and media files from development server
#     urlpatterns += staticfiles_urlpatterns()
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analyzes_records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from analyzes_records.views import (
    CalendarView,
    CreateAnalysisView,
    LabTestDetailView,
    LabTestListView,
)

app_name = "analyzes_records"

urlpatterns = [
    path("", LabTestListView.as_view(), name="test_list"),
    path("calendar/analysis/<int:pk>", LabTestDetailView.as_view(), name="analysis"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("analysis/add/", CreateAnalysisView.as_view(), name="add_analysis"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

health_indicators/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from health_indicators.views import (
    CreateIndicatorView,
    IndicatorDetailView,
    IndicatorListView,
)

app_name = "health_indicators"

urlpatterns = [
    path("", IndicatorListView.as_view(), name="indicator_list"),
    path("indicator/<int:pk>", IndicatorDetailView.as_view(), name="indicator"),
    # path("calendar/", CalendarView.as_view(), name="calendar"),
    path("indicator/add/", CreateIndicatorView.as_view(), name="add_indicator"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.views import (
    ChangePasswordView,
    contact,
    edit_profile,
    index,
    login_user,
    logout_view,
    register,
)

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("contact/", contact, name="contact"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login_user"),
    path("logout/", logout_view, name="logout"),
    path("profile/", edit_profile, name="edit_profile"),
    path("change_password/", ChangePasswordView.as_view(), name="password_change"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

visit_records/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from visit_records.views import (
    AppointmentDetailView,
    AppointmentListView,
    CreateAppointmentView,
)

app_name = "visit_records"

urlpatterns = [
    path("", AppointmentListView.as_view(), name="visit_list"),
    path("appointment/<int:pk>", AppointmentDetailView.as_view(), name="appointment"),
    path("add_appointment/", CreateAppointmentView.as_view(), name="add_appointment"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

from django.core.validators import MaxValueValidator, MinValueValidator


class Profile(models.Model):
    BLOOD_TYPE_CHOICES = [
        ("O+", "O+"),
        ("O-", "O-"),
        ("A+", "A+"),
        ("A-", "A-"),
        ("B+", "B+"),
        ("B-", "B-"),
        ("AB+", "AB+"),
        ("AB-", "AB-"),
    ]

    GENDER_CHOICES = [
        ("0", "male"),
        ("1", "female"),
        ("2", "other"),
    ]

    TRUE_FALSE_CHOICES = ((True, "Yes"), (False, "No"))

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="Username",
    )
    date_of_birth = models.DateField(
        blank=True,
        null=True,
        validators=[
            MaxValueValidator(date.today()),
            MinValueValidator(date(1900, 1, 1)),
        ],
    )
    blood_type = models.CharField(
        max_length=3, choices=BLOOD_TYPE_CHOICES, blank=True, null=True
    )
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, blank=True, null=True
    )
    height = models.IntegerField(
        blank=True,
        null=True,
        help_text="in cm",
        validators=[MaxValueValidator(300), MinValueValidator(40)],
    )
    weight = models.IntegerField(
        blank=True,
        null=True,
        help_text="in kg",
        validators=[MaxValueValidator(650), MinValueValidator(2)],
    )

    def __str__(self):
        return f"Profile for user {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from users.models import Profile


def validate_password_strength(value):
    """Validates that a password is as least 7 characters long and has at least
    1 digit and 1 letter.
    """
    min_length = 7

    if len(value) < min_length:
        raise ValidationError(
            _("Password must be at least {0} characters " "long.").format(min_length)
        )

    # check for digit
    if not any(char.isdigit() for char in value):
        raise ValidationError(_("Password must contain at least 1 digit."))

    # check for letter
    if not any(char.isalpha() for char in value):
        raise ValidationError(_("Password must contain at least 1 letter."))


class RegisterForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(min_length=8, widget=forms.PasswordInput())
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        if validate_password_strength(cd["password"]):
            raise forms.ValidationError("Passwords are too short.")
        return cd["password2"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, label="Email")
    password = forms.CharField(min_length=8, widget=forms.PasswordInput())


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())
    first_name = forms.CharField(
        max_length=100, required=True, widget=forms.TextInput()
    )
    last_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class ProfileEditForm(forms.ModelForm):

    BLOOD_TYPE_CHOICES = (
        ("O+", "O+"),
        ("O-", "O-"),
        ("A+", "A+"),
        ("A-", "A-"),
        ("B+", "B+"),
        ("B-", "B-"),
        ("AB+", "AB+"),
        ("AB-", "AB-"),
    )

    GENDER_CHOICES = (
        ("0", "male"),
        ("1", "female"),
        ("2", "other"),
    )

    date_of_birth = forms.DateField(
        required=True, widget=forms.SelectDateWidget(years=range(1900, 2100))
    )
    blood_type = forms.ChoiceField(
        choices=BLOOD_TYPE_CHOICES, required=True, widget=forms.Select()
    )
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES, required=True, widget=forms.Select()
    )
    height = forms.CharField(max_length=10, required=True, widget=forms.TextInput())
    weight = forms.CharField(max_length=10, required=True, widget=forms.TextInput())

    class Meta:
        model = Profile
        fields = ("date_of_birth", "blood_type", "gender", "height", "weight")

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from .forms import LoginForm, ProfileEditForm, RegisterForm, UpdateUserForm
from .services import create_user


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = "users/change_password.html"
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy("users:edit_profile")


def index(request):
    return render(request, "dashboard.html")


def contact(request):
    return render(request, "contact.html")


def validate_password_strength(value):
    """Validates that a password is as least 7 characters long and has at least
    1 digit and 1 letter.
    """
    min_length = 7

    if len(value) < min_length:
        raise ValidationError(
            _("Password must be at least {0} characters " "long.").format(min_length)
        )

    # check for digit
    if not any(char.isdigit() for char in value):
        raise ValidationError(_("Password must contain at least 1 digit."))

    # check for letter
    if not any(char.isalpha() for char in value):
        raise ValidationError(_("Password must contain at least 1 letter."))


def register(request):
    if request.user.is_authenticated:
        return redirect("/")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            create_user(
                email=form.cleaned_data["email"],
                username=form.cleaned_data["email"],
                password=form.cleaned_data["password"],
            )
            return redirect("users:login_user")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form": form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect("/")

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request=request, **form.cleaned_data)
            if user is None:
                return HttpResponse("BadRequest", status=400)
            login(request, user)
            # if request.user.last_login.time request.user.date_joined.time:
            #     return redirect("users:edit_profile")
            # else:
            return redirect("/")
    else:
        form = LoginForm()
    return render(request, "users/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("/")


@login_required
def edit_profile(request):
    if request.method == "POST":
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated successfully")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(
        request,
        "users/profile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )

templates/users/change_password.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_filters %}

{% block title %}Profile{% endblock %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark z-index-9  fixed-top" id="mainNav">

        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav navbar-sidenav background-main-color admin-nav" id="admin-nav">
                <li class="nav-item">
                    <span class="nav-title-text">Main</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url "users:index" %}">
                        <i class="fas fa-fw fa-home"></i><span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "visit_records:visit_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Appointments</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:test_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Analyzes</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:calendar" %}">
                        <i class="fa fa-fw fa-calendar"></i>
                        <span class="nav-link-text">Analyzes Calendar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "health_indicators:indicator_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Indicators</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">Add Pages</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "visit_records:add_appointment" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Appointment</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "analyzes_records:add_analysis" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Analysis</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "health_indicators:add_indicator" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Indicator</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">User Area</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Profile">
                    <a class="nav-link" href="{% url "users:edit_profile" %}">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="nav-link-text">My Profile</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sing Out">
                    <a class="nav-link" href="{% url "users:logout" %}" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out-alt"></i>
                        <span class="nav-link-text">Sing Out</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container text-center">
            <ol class="breadcrumb opacity-5">
                <li><a href="{% url "users:index" %}">Home</a></li>
                <li class="active">Change password</li>
            </ol>
            <h1 class="font-weight-300">Change password</h1>
        </div>
    </div>

    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="container margin-bottom-10px">
        <!--======= log_in_page =======-->
        <div id="log-in" class="site-form log-in-form box-shadow border-radius-10">
            <div class="form-output">
                <form method="POST" enctype="multipart/form-data" class="post-form">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-10 offset-md-1">
                            <div class="form-group">
                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                <input type="password" name="old_password" autocomplete="new-password"
                                       class="form-control" required id="id_old_password"
                                       placeholder="Enter Old Password"/>
                                <span>
                                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-10 offset-md-1">
                            <div class="form-group">
                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                <input type="password" name="new_password1" autocomplete="new-password"
                                       class="form-control" required id="id_new_password1"
                                       placeholder="Enter New Password"/>
                                <span>
                                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-10 offset-md-1">
                            <div class="form-group">
                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                <input type="password" name="new_password2" autocomplete="new-password"
                                       required id="id_new_password2" class="form-control"
                                       placeholder="Confirm New Password"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-10 offset-md-1">
                            <div class="form-group mt-0 mb-1">
                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_filters %}

{% block title %}Login{% endblock %}

{% block content %}

     <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container text-center">
            <ol class="breadcrumb opacity-5">
                <li><a href="{% url "users:index" %}">Home</a></li>
                <li class="active">Login</li>
            </ol>
            <h1 class="font-weight-300">Login Page</h1>
        </div>
    </div>

    <div class="container margin-bottom-10px">
        <!--======= log_in_page =======-->
        <div id="log-in" class="site-form log-in-form box-shadow border-radius-10">
            <div class="form-output">
                <form method="POST" class="post-form">
                    {{ form|crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Login</button>
                    <div class="or"></div>
                    <p>Don't you have an account? <a href="{% url "users:register" %}">Register Now!</a></p>
                </form>
            </div>
        </div>
        <!--======= // log_in_page =======-->
    </div>
{% endblock %}

templates/users/profile.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_filters %}

{% block title %}Profile{% endblock %}

{% block content %}

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark z-index-9  fixed-top" id="mainNav">

        <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav navbar-sidenav background-main-color admin-nav" id="admin-nav">
                <li class="nav-item">
                    <span class="nav-title-text">Main</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url "users:index" %}">
                        <i class="fas fa-fw fa-home"></i><span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "visit_records:visit_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Appointments</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:test_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Analyzes</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "analyzes_records:calendar" %}">
                        <i class="fa fa-fw fa-calendar"></i>
                        <span class="nav-link-text">Analyzes Calendar</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My items">
                    <a class="nav-link" href="{% url "health_indicators:indicator_list" %}">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">My Indicators</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">Add Pages</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "visit_records:add_appointment" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Appointment</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "analyzes_records:add_analysis" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Analysis</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add Listing">
                    <a class="nav-link active" href="{% url "health_indicators:add_indicator" %}">
                        <i class="fa fa-fw fa-plus-circle"></i>
                        <span class="nav-link-text">Add Indicator</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-title-text">User Area</span>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Profile">
                    <a class="nav-link" href="{% url "users:edit_profile" %}">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="nav-link-text">My Profile</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sing Out">
                    <a class="nav-link" href="{% url "users:logout" %}" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out-alt"></i>
                        <span class="nav-link-text">Sing Out</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container text-center">
            <ol class="breadcrumb opacity-5">
                <li><a href="{% url "users:index" %}">Home</a></li>
                <li class="active">Profile</li>
            </ol>
            <h1 class="font-weight-300">Edit profile</h1>
        </div>
    </div>

    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="container margin-bottom-10px">
        <!--======= log_in_page =======-->
        <div id="log-in" class="site-form log-in-form box-shadow border-radius-10">
            <div class="form-output">
                <form method="POST" enctype="multipart/form-data" class="post-form">

                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="small mb-1">Username:</label>
                                {{ user_form.username }}
                                <label class="small mb-1">Email:</label>
                                {{ user_form.email }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1">First name:</label>
                                {{ user_form.first_name }}
                                <label class="small mb-1">Last name:</label>
                                {{ user_form.last_name }}
                                <label class="small mb-1">Date of birth:</label>
                                {{ profile_form.date_of_birth }}
                                <br>
                                <label class="small mb-1">Blood type:</label>
                                {{ profile_form.blood_type }}
                                <label class="small mb-1">Gender:</label>
                                {{ profile_form.gender }}
                                <label class="small mb-1">Height:</label>
                                {{ profile_form.height }}
                                <label class="small mb-1">Weight:</label>
                                {{ profile_form.weight }}
                            </div>
                            <div class="form-group">
                                <a href="{% url 'users:password_change' %}">Change Password</a>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/register.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_filters %}

{% block title %}Registration{% endblock %}

{% block content %}

    <div id="page-title" class="padding-tb-30px gradient-white">
        <div class="container text-center">
            <ol class="breadcrumb opacity-5">
                <li><a href="{% url "users:index" %}">Home</a></li>
                <li class="active">Sing Up</li>
            </ol>
            <h1 class="font-weight-300">Sing Up Page</h1>
        </div>
    </div>

    <div class="container margin-bottom-10px">
        <!--======= log_in_page =======-->
        <div id="log-in" class="site-form log-in-form box-shadow border-radius-10">
            <div class="form-output">
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Complete  sign up!</button>
                    <div class="or"></div>
                    <p>Already have an account? <a href="{% url "users:login_user" %}"> Sing in !</a></p>
                </form>
            </div>
        </div>
        <!--======= // log_in_page =======-->
    </div>
{% endblock %}